# Generated by Django 5.0.1 on 2024-02-01 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_skills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
