# Generated by Django 5.0.1 on 2024-02-27 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_profile_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['created']},
        ),
    ]
